# Generated by Django 5.1.2 on 2024-10-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SleepLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sleep_duration', models.FloatField(help_text='Продолжительность сна в часах')),
                ('sleep_start_time', models.TimeField(help_text='Время начала сна')),
                ('sleep_quality', models.CharField(choices=[('excellent', 'Отлично'), ('good', 'Хорошо'), ('average', 'Средне'), ('poor', 'Плохо')], max_length=10)),
            ],
        ),
    ]
