# Generated by Django 5.1.2 on 2024-10-26 10:48

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleep', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleeplog',
            name='date',
            field=models.DateField(validators=[utils.validators.validate_date]),
        ),
        migrations.AlterField(
            model_name='sleeplog',
            name='sleep_duration',
            field=models.FloatField(help_text='Продолжительность сна в часах', validators=[utils.validators.validate_sleep_hours]),
        ),
    ]
