# Generated by Django 5.1.2 on 2024-10-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleep', '0003_alter_sleeplog_date_alter_sleeplog_sleep_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleeplog',
            name='sleep_quality',
            field=models.CharField(choices=[(10, 'Отлично'), (7, 'Хорошо'), (4, 'Средне'), (1, 'Плохо')], max_length=10),
        ),
    ]
