# Generated by Django 5.1.2 on 2024-10-27 09:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sleep', '0005_remove_sleeplog_sleep_start_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sleeplog',
            unique_together={('user', 'date')},
        ),
    ]
