# Generated by Django 5.1.2 on 2024-10-27 13:38

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_alter_stepslog_date_alter_stepslog_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepslog',
            name='feeling',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[utils.validators.validate_feeling_level]),
        ),
    ]
