# Generated by Django 5.1.2 on 2024-10-26 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='meal',
        ),
        migrations.CreateModel(
            name='MealProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Количество продукта в приёме пищи')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_products', to='food.meallog')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_products', to='food.product')),
            ],
            options={
                'unique_together': {('meal', 'product')},
            },
        ),
    ]
