# Generated by Django 5.1.2 on 2024-10-26 10:48

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_remove_product_meal_mealproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meallog',
            name='date',
            field=models.DateField(validators=[utils.validators.validate_date]),
        ),
        migrations.AlterField(
            model_name='product',
            name='calories',
            field=models.PositiveIntegerField(help_text='Калорийность продукта', validators=[utils.validators.validate_calories]),
        ),
    ]
