# Generated by Django 5.1.2 on 2024-10-27 10:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_remove_product_user_delete_mealproduct_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meallog',
            unique_together={('user', 'date')},
        ),
    ]
