# Generated by Django 5.1.2 on 2024-10-27 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_alter_meallog_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meallog',
            unique_together=set(),
        ),
    ]
