# Generated by Django 5.1.2 on 2024-10-26 10:48

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.PositiveSmallIntegerField(default=0, validators=[utils.validators.validate_age]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='height',
            field=models.FloatField(blank=True, null=True, validators=[utils.validators.validate_height], verbose_name='Рост'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='weight',
            field=models.FloatField(blank=True, null=True, validators=[utils.validators.validate_weight], verbose_name='Вес'),
        ),
    ]
